name: Validate Schemas

on:
  push:
    branches:
      - main

jobs:
  kubeval-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3
      - name: Run kubeconform
        run: .github/kubeconform.sh
